"use client";

import { Bot, Lightbulb, Presentation, Rocket, Sparkles, X } from "lucide-react";
import Image from "next/image";
import { useState } from "react";
import styles from "./innovation.module.css";

const pathways = [{ title: "Generate Your Idea", description: "Identify your challenge, brainstorm solutions, and refine your concept with AI.", image: "/innovation/generate-idea.png" }, { title: "Create Your Pitch Deck", description: "Outline your problem, develop solutions, and enhance your deck with AI insights.", image: "/innovation/pitch-deck.png" }, { title: "Pitch to AI Coach", description: "Present your pitch, receive feedback, and improve your delivery with AI guidance.", image: "/innovation/ai-coach.png" }];

export default function InnovationPage() {
	const [projects, setProjects] = useState([]);
	const [view, setView] = useState("home");
	const [form, setForm] = useState({ name: "", idea: "", audience: "", problem: "", note: "" });
	const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
	const createProject = () => { if (!form.name.trim()) return; setProjects((items) => [{ title: form.name, updated: "Edited just now" }, ...items]); setForm({ name: "", idea: "", audience: "", problem: "", note: "" }); setView("home"); };
	const generateIdeas = () => { if (!form.idea.trim() && !form.problem.trim()) return; setProjects((items) => [{ title: form.name || "New impact idea", updated: "AI ideas generated now" }, ...items]); };
	return <main className={styles.workspace}><section className={styles.panel}><header><div><span>INNOVATION PLAYGROUND</span><h1>{view === "home" ? "Make a difference with your ideas" : "What’s your big idea?"}</h1></div><div><button type="button" onClick={() => setView("home")} className={view === "home" ? styles.outline : ""}>Explore programs</button></div></header>{view === "home" ? <Home projects={projects} setView={setView} setProjects={setProjects} /> : <IdeaForm form={form} update={update} generateIdeas={generateIdeas} createProject={createProject} projects={projects} />}</section></main>;
}
function Home({ projects, setView, setProjects }) {
	const [openProject, setOpenProject] = useState(null);
	const [deleteTarget, setDeleteTarget] = useState(null);
	const deleteProject = (index) => {
		setProjects((items) => items.filter((_, itemIndex) => itemIndex !== index));
		setDeleteTarget(null);
	};
	return <><div className={styles.pathways}>{pathways.map((path) => <button type="button" key={path.title} onClick={() => setView("new")} className={styles.pathway}><span className={styles.pathwayArt}><Image src={path.image} alt="" fill sizes="(max-width: 760px) 100vw, 33vw" /></span><h2>{path.title}</h2><p>{path.description}</p><i>Start <Rocket size={14} /></i></button>)}</div><section className={styles.recent}><h2>Recent projects</h2>{projects.length ? <div>{projects.map((project, index) => <article key={`${project.title}-${index}`}><strong>{project.title}</strong><small>{project.updated}</small><button type="button" aria-label={`Project options for ${project.title}`} onClick={() => setOpenProject(openProject === index ? null : index)}>⋮</button>{openProject === index && <div className={styles.projectMenu}><button type="button" onClick={() => { setDeleteTarget(index); setOpenProject(null); }}>Delete project</button></div>}</article>)}</div> : <p className={styles.noProjects}>No recent projects yet.</p>}</section>{deleteTarget !== null && <div className={styles.deleteOverlay} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setDeleteTarget(null); }}><section className={styles.deleteDialog} role="dialog" aria-modal="true" aria-labelledby="delete-project-title"><h2 id="delete-project-title">Delete project?</h2><p>This project will be removed from your recent projects.</p><div><button type="button" className={styles.cancelDelete} onClick={() => setDeleteTarget(null)}>Cancel</button><button type="button" className={styles.confirmDelete} onClick={() => deleteProject(deleteTarget)}>Delete</button></div></section></div>}</>;
}
function IdeaForm({ form, update, generateIdeas, createProject, projects }) { return <div className={styles.ideaLayout}><form onSubmit={(event) => { event.preventDefault(); createProject(); }}><label>Idea Name<input value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Name your project" required /></label><label>What&apos;s your idea?<textarea value={form.idea} onChange={(event) => update("idea", event.target.value)} placeholder="Describe your idea, problem, and solution..." /></label><label>Who will your idea help?<input value={form.audience} onChange={(event) => update("audience", event.target.value)} placeholder="e.g. Students, schools, working professionals" /></label><label>What problem does your idea solve?<textarea value={form.problem} onChange={(event) => update("problem", event.target.value)} placeholder="What problem did you notice that made you think of this idea?" /></label><label>Anything else you&apos;d like us to know?<textarea value={form.note} onChange={(event) => update("note", event.target.value)} placeholder="Add useful context for your project" /></label><button type="button" className={styles.generate} onClick={generateIdeas}><Sparkles size={15} /> Generate Ideas</button><button type="submit" className={styles.save}>Save project</button></form><aside><h2>Your startup ideas</h2>{projects.length ? projects.map((project, index) => <article key={index}><Lightbulb size={20} /><div><strong>{project.title}</strong><p>{project.updated}</p></div></article>) : <div className={styles.emptyIdeas}><Lightbulb size={42} /><strong>No ideas generated yet</strong><p>Fill out the form and click “Generate Ideas” to discover creative startup ideas!</p></div>}</aside></div>; }
