import Image from "next/image";
import Link from "next/link";
import { Building2, Rocket, Sparkles } from "lucide-react";

const institutions = [
  { icon: Building2, name: "Greenwood Academy", type: "Secondary Education", story: "Integrated iGyanAI to automate venture coaching, resulting in a 40% increase in student venture readiness within the first semester.", stats: [["1.2k", "Hours Saved"], ["92%", "Success Boost"]] },
  { icon: Sparkles, name: "Oxford Academy", type: "Collegiate Hub", story: "Established a dedicated AI Venture Studio, streamlining the path from student research to viable commercialized startups.", stats: [["14", "New Patents"], ["$2.4M", "Seed Capital"]] },
  { icon: Building2, name: "St. Jude’s Prep", type: "Community Focused", story: "Leveraging Capital Readiness metrics to connect underrepresented student founders with institutional grant opportunities.", stats: [["65%", "Grant Access"], ["310", "Active Founders"]] },
];

const students = [
  { name: "Marcus Chen", venture: "Founder of Nexus AI", score: "92", story: "Developed a sustainable community logistics platform using VentureStudio's AI scaffolding.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDkpRRFvSBMQ-3744PTUNS4_ZZyyJwSzEdzBcoPBs5Jp0n_8FnEM8MXUh2kq3aU-tRtkpHMv1FRIfVozN2QpqW-jc8ORZx7wGB264M4cXAin_Pg6hLUPC-0EDpMTIF3zN_h6p7P5oIrI8rMmI_hwxJetRbddxWztuBPHRifSETQhV1JBzcvjYuKx-6g7_CJG04upMIwINzYz-tI5Oz2BwYf9-dyI5RKXHSWR4yCwlMMN9oFPU7oUned" },
  { name: "Sarah Jenkins", venture: "Founder of EcoStream", score: "88", story: "Leveraged OXA's Venture Studio to scale a biotech recycling solution from lab to prototype.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC6Szg58gqB48IihmAbXqPxquztChHXWzy1BnsxyGTj0ZHi_3qjYDW8DvFT-rh4No-PkT2NqDOy6U2N50glIb5vAfcGBum49zvSdc4dJK-HcNJFLYcymklGsGieklxUoPk6wf5baOheR0bYgcq9r3CIy1_zynoGWtWTKG7Y_ljSj_omAKs1xBmy-KZjX70TAcqMNS_OGSkPUbEPLDbSlWYiCcx92kP9yv1bbRwBn13tOaTC8DygiIk_" },
  { name: "Aditya Rao", venture: "Founder of FinPath AI", score: "95", story: "Secured $100k in institutional funding after achieving a near-perfect Capital Readiness rating.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCPfTJnu9yDQCAdcxv8BKxKWKdeRuakn8jyNtIb1XV2DuzsgflAb-IqbYmAzu8UPVKzs0bz4vFC0myBA7nqZp9MaMf6LuO_DtYBhrQeXRDMVQi8WwOC2Tu579U021hCc6iykMDd3rk3UwB52hN8v-Qn_RlMn1KIqxzovsfjLh1df6ew7RI0idb1ZVg0b1asyz9HEyiRTLmz-H4lWtbny8TediYtflRV4Dix4-p_s7CuHfaXa69q2QYG" },
  { name: "Elena Vance", venture: "Founder of SpeakUp", score: "86", story: "An accessibility-focused SaaS platform that pivoted successfully using AI market intelligence.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAS_Ki543I1fhjjJsgydh05a7BlrNL9j1KNVC4KT3nZ0K_F-5HKAlaUMX0x_fttBpLJwjf6aFZh7ZnQ1rPgoWRsqBfrOUkqG4CZj0YJmaBeKChNYycDgLV6HiVFVvuZOD0qtKVKNTXnp8b9eLSuhtYF4-UnpySF3gGK3CeNeVvmMa0WhwRS0xWnVWcD4S8jLBfpM5sjVs_Scm1bIGhAUb8UIbgd-YQODlINJBWMk8Z4kLoVL-rwMFd2" },
  { name: "Leo & Maya", venture: "Founders of PrintFast", score: "91", story: "Revolutionizing desktop manufacturing with on-demand AI optimization for student projects.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB1V9DCMk-ABoLaGjo9n398rswn2AjNU6A4OjVuUP4ixYne3h4qLXIHMtRq7ZKgglietzJcDiChuqHqPOhhQ-g3hEu3WsrSvmNDlFCJTd_zdSbh6VXs4Lu_fjYcrRDs4unLJCyBskMfZnte8yWL9c5vDkK448-POxrJwHzDidcigeK6As2Z_hoVSpaPAsEEm4xTj7Ql3GmAfDLqinXon_DJ9V_ggc0hZ-z86_A7uQVNZfXvRrWxGJiz" },
  { name: "Jordan Wu", venture: "Founder of StudyFlow", score: "89", story: "Using AI to personalize curriculum-based venture development for first-time founders.", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBS0IBRydIl6XYQKQV4dbKMMG62VzYjCMnYLwPShNPdfRTmhjc5tL_alf5UmRpptaM5DBS0vSGX6k68_uzlKhWhTCitIK7Ki-O8ReD0V0LsU3U5NBbb1d7lOCF3xf2j6iVMjv6t4aEU7QHcs6GS4SfeLTvADPz2cts6NdoeDWGGgdmhXnLNKnsNnwpP2VDjhRX84Qlh6aYzCNtqKyUyfdNdvDB8T_REBeLLlk-EgIqYrCnGGf0sXwea" },
];

export const metadata = { title: "Success Stories | IGYAN AI" };

export default function SuccessStoriesPage() {
  return <main className="overflow-x-clip bg-white text-slate-900">
    <section className="relative overflow-hidden bg-gradient-to-b from-[#fff5ec] via-[#ece5ff] to-white px-6 py-20 text-center sm:px-10 md:py-28">
      <div className="absolute left-1/2 top-1/2 h-[32rem] w-[32rem] -translate-x-1/2 -translate-y-1/2 rounded-full bg-indigo-300/20 blur-3xl" />
      <div className="relative mx-auto max-w-3xl"><h1 className="mt-6 text-4xl font-extrabold tracking-tight text-[#1e1b4b] sm:text-5xl">Voices of Innovation</h1><p className="mt-6 text-lg leading-relaxed text-slate-600">Celebrating the student founders and visionary institutions reshaping education through AI-driven venture acceleration.</p></div>
    </section>

    <section className="px-6 py-20 sm:px-10 md:py-28"><div className="mx-auto max-w-6xl"><SectionHeading icon={Building2} title="Institutional Impact" /><div className="grid gap-6 md:grid-cols-3">{institutions.map((institution) => { const Icon = institution.icon; return <article key={institution.name} className="flex flex-col rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-indigo-50 text-[#3b1595]"><Icon className="h-6 w-6" /></span><div><h2 className="font-bold text-[#1e1b4b]">{institution.name}</h2><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{institution.type}</p></div></div><p className="mt-6 flex-1 leading-relaxed text-slate-600">{institution.story}</p><div className="mt-7 grid grid-cols-2 gap-3">{institution.stats.map(([value, label]) => <div key={label} className="rounded-xl bg-indigo-50 p-3 text-center"><p className="text-xl font-extrabold text-[#3b1595]">{value}</p><p className="mt-1 text-xs font-semibold text-slate-500">{label}</p></div>)}</div></article>; })}</div></div></section>

    <section className="bg-slate-50 px-6 py-20 sm:px-10 md:py-28"><div className="mx-auto max-w-6xl"><SectionHeading icon={Rocket} title="Student Spotlights" /><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{students.map((student) => <article key={student.name} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-64"><Image src={student.image} alt={student.name} fill className="object-cover" sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" /><span className="absolute right-4 top-4 inline-flex items-center gap-1 rounded-full bg-[#3b1595] px-3 py-1.5 text-xs font-bold text-white"><Sparkles className="h-3.5 w-3.5" />{student.score} Shark Score</span></div><div className="p-6"><h2 className="text-xl font-bold text-[#1e1b4b]">{student.name}</h2><p className="mt-1 text-sm font-bold text-[#064bb2]">{student.venture}</p><p className="mt-4 text-sm leading-relaxed text-slate-600">{student.story}</p></div></article>)}</div></div></section>

    <section className="bg-[#3b1595] px-6 py-16 text-white sm:px-10 md:py-20"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-7 md:flex-row"><div className="max-w-2xl text-center md:text-left"><h2 className="text-3xl font-extrabold tracking-tight">Share Your Journey</h2><p className="mt-4 leading-relaxed text-indigo-100">Are you an institution scaling innovation or a student building the future? Tell us your story and join our community.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="rounded-full bg-white px-6 py-3 text-center font-bold text-[#3b1595] transition hover:bg-indigo-50">Submit Success Story</Link><Link href="/contact" className="rounded-full border border-white/50 px-6 py-3 text-center font-bold transition hover:bg-white/10">Contact Partners</Link></div></div></section>
  </main>;
}

function SectionHeading({ icon: Icon, title }) { return <div className="mb-10 flex items-center gap-3"><Icon className="h-7 w-7 text-[#3b1595]" /><h2 className="text-3xl font-extrabold tracking-tight text-[#1e1b4b]">{title}</h2><span className="ml-4 hidden h-px flex-1 bg-slate-200 md:block" /></div>; }
